apiVersion: v1
kind: Service
metadata:
  name: aws-bookstore-backend
  annotations:
    prometheus.io/port: "backend-api"
    prometheus.io/scrape: "true"
  labels: 
    app.kubernetes.io/part-of: bookstore
spec:
  selector:
    app: aws-bookstore-backend
    tier: backend
  ports:
    - protocol: TCP
      name: backend-api
      port: 5000
      targetPort: 5000
  type: ClusterIP
  
