apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aws-bookstore-backend
spec:
  endpoints:
    - interval: 15s
      port: backend-api
      scrapeTimeout: 14s
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dms
