apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-bookstore-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-bookstore-backend
  template:
    metadata:
      labels:
        app: aws-bookstore-backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: aws-bookstore-backend
          image: public.ecr.aws/f2m3w5c9/bookstore-api:5
          ports:
            - name: http
              containerPort: 5000
