apiVersion: v1
kind: Service
metadata:
  name: aws-bookstore-backend
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrap: "true"
  labels: 
    app.kubernetes.io/part-of: dms
spec:
  selector:
    app: aws-bookstore-backend
    tier: backend
  ports:
    - protocol: TCP
      name: backend-service
      port: 5000
      targetPort: 5000
  type: ClusterIP
  
