apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-app
  template:
    metadata:
      labels:
        app: bookstore-app
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: mwyssy/bookstore-frontend-api:1.7
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: bookstore-backend
