apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend
spec:
  selector:
    app: bookstore-app
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
