apiVersion: v1
kind: Service
metadata:
  name: bookstore-frontend-service
spec:
  selector:
    app: bookstore-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
